"""TDPI (Test-Driven Performance Iteration) loop for candle-fork QLoRA.

Goal: replace "guess and check" with measured A/B comparison. Runs an
autonomous loop that:

  1. Pulls the next hypothesis from HYPOTHESES.json (ranked).
  2. If the hypothesis names a CLI flag combination, just runs the bench
     against the current binary with that combination — no code change.
     Otherwise, the hypothesis names a feature branch + a code change to
     apply (currently out of scope for the autonomous loop; logged for
     manual implementation).
  3. Compares the run's measured deltas against BENCH_BASELINE.json under
     the appropriate preset.
  4. Acceptance criterion (per hypothesis):
       - Primary metric (tok_per_sec OR peak_vram_mb depending on intent)
         must improve by >= the threshold specified in the hypothesis.
       - Other metrics must not REGRESS by more than their per-metric
         tolerance (default: 5% degradation triggers reject).
  5. Logs the verdict (accept / reject / inconclusive) to PERF_LOG.md
     with the measured deltas. On accept, updates BENCH_BASELINE.json
     in place (previous value goes into history list).

Constraints:
  * Never touch git history or commits — this loop only RUNS benches.
    Code-change hypotheses are flagged for human follow-up.
  * Each bench is one full run (3 warmup + 20 measured) — call it ~20 min.
  * Cooldown between runs: 60s (allows GPU thermals to settle).
  * Hard wall-clock cap: 4 hours (configurable via --max-hours).

Usage:
  python bench/tdpi-loop.py --max-hours 4
  python bench/tdpi-loop.py --hypothesis-only F  # run just one
  python bench/tdpi-loop.py --dry-run            # plan, don't execute
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import subprocess
import sys
import time
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent  # J:/candle-src
BENCH_DIR = ROOT / "bench"
RESULTS_DIR = BENCH_DIR / "results"
BASELINE_PATH = BENCH_DIR / "BENCH_BASELINE.json"
HYPOTHESES_PATH = BENCH_DIR / "HYPOTHESES.json"
PERF_LOG_PATH = BENCH_DIR / "PERF_LOG.md"
RUNNER = BENCH_DIR / "run-bench.ps1"

HOST = os.environ.get("COMPUTERNAME", "unknown").lower()
COOLDOWN_SECONDS = 60


def load_json(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def write_json(p: Path, data: dict) -> None:
    p.write_text(json.dumps(data, indent=2), encoding="utf-8")


def append_perf_log(entry: str) -> None:
    PERF_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not PERF_LOG_PATH.exists():
        PERF_LOG_PATH.write_text(
            "# PERF_LOG.md\n\nAuto-generated by bench/tdpi-loop.py. "
            "Each entry is one hypothesis evaluated against the locked "
            "baseline.\n\n",
            encoding="utf-8",
        )
    with PERF_LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(entry)


def run_bench(preset: str, dry_run: bool) -> dict | None:
    """Invoke run-bench.ps1 with the preset. Returns parsed result dict or None."""
    if dry_run:
        print(f"[dry-run] would run preset={preset}")
        return None
    cmd = ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass",
           "-File", str(RUNNER), preset]
    print(f"[bench] starting preset={preset}", flush=True)
    proc = subprocess.run(cmd, cwd=str(ROOT))
    if proc.returncode != 0:
        print(f"[bench] FAILED rc={proc.returncode}", flush=True)
        return None
    # Locate the JSON output (run-bench writes <preset>-<commit>.json).
    commit = subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"], cwd=str(ROOT)
    ).decode().strip()
    json_path = RESULTS_DIR / f"{preset}-{commit}.json"
    if not json_path.exists():
        print(f"[bench] no result file at {json_path}", flush=True)
        return None
    return load_json(json_path)


def compare(result: dict, baseline: dict, hypothesis: dict) -> tuple[str, str]:
    """Return ('accept'|'reject'|'inconclusive', explanation)."""
    primary = hypothesis.get("primary_metric", "tok_per_sec")
    direction = hypothesis.get("direction", "increase")  # or "decrease" for VRAM
    threshold = hypothesis.get("threshold_pct", 2.0) / 100.0
    tolerance_pct = hypothesis.get("regression_tolerance_pct", 5.0) / 100.0

    base_v = baseline[primary]
    new_v = result[primary]

    if base_v == 0:
        return "inconclusive", f"baseline {primary}=0; cannot compute ratio"

    if direction == "increase":
        delta_pct = (new_v - base_v) / base_v
        primary_pass = delta_pct >= threshold
    elif direction == "decrease":
        delta_pct = (base_v - new_v) / base_v
        primary_pass = delta_pct >= threshold
    else:
        return "inconclusive", f"unknown direction {direction!r}"

    # Check guard metrics for non-regression.
    guards = []
    for metric in ("tok_per_sec", "peak_vram_mb", "step_ms_median"):
        if metric == primary:
            continue
        b = baseline.get(metric)
        n = result.get(metric)
        if b is None or n is None or b == 0:
            continue
        # tok_per_sec: regression = decrease.
        # peak_vram_mb / step_ms: regression = increase.
        if metric == "tok_per_sec":
            reg = (b - n) / b
        else:
            reg = (n - b) / b
        if reg > tolerance_pct:
            guards.append(f"{metric} regressed {reg*100:.1f}%")

    if not primary_pass:
        return (
            "reject",
            f"{primary} {direction} {delta_pct*100:+.2f}% < threshold {threshold*100:.1f}%",
        )
    if guards:
        return (
            "reject",
            f"primary OK ({delta_pct*100:+.2f}%) but regressions: {'; '.join(guards)}",
        )
    return "accept", f"{primary} {direction} {delta_pct*100:+.2f}% (>= {threshold*100:.1f}%); no regressions"


def update_baseline(host: str, preset: str, result: dict) -> None:
    baseline = load_json(BASELINE_PATH)
    presets = baseline.setdefault(host, {}).setdefault("presets", {})
    history = presets.setdefault(preset, {}).setdefault("_history", [])
    if "commit" in presets[preset]:
        history.append({k: presets[preset][k] for k in presets[preset] if not k.startswith("_")})
    presets[preset].update({
        "commit": result["commit"],
        "branch": result["branch"],
        "verified_run_at": result["run_at"],
        "tok_per_sec": result["tok_per_sec"],
        "step_ms_median": result["step_ms_median"],
        "step_ms_p95": result["step_ms_p95"],
        "peak_vram_mb": result["peak_vram_mb"],
        "mean_gpu_util": result["mean_gpu_util"],
        "log_file": result["log_file"],
    })
    write_json(BASELINE_PATH, baseline)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-hours", type=float, default=4.0)
    ap.add_argument("--hypothesis-only", default=None)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--host", default=HOST)
    args = ap.parse_args()

    if not HYPOTHESES_PATH.exists():
        print(f"missing {HYPOTHESES_PATH}; create it first", flush=True)
        return 2
    hypotheses = load_json(HYPOTHESES_PATH)["hypotheses"]

    if args.hypothesis_only:
        hypotheses = [h for h in hypotheses if h["id"] == args.hypothesis_only]
        if not hypotheses:
            print(f"no hypothesis with id={args.hypothesis_only}", flush=True)
            return 2

    deadline = time.time() + args.max_hours * 3600
    summary: list[dict] = []

    for h in hypotheses:
        if time.time() > deadline:
            print(f"[loop] {args.max_hours}h elapsed; stopping", flush=True)
            break
        if h.get("requires_code_change"):
            print(f"[loop] skipping {h['id']}: requires code change; flagged for manual", flush=True)
            append_perf_log(
                f"## [{dt.datetime.now().isoformat(timespec='seconds')}] {h['id']} — DEFERRED\n"
                f"- {h['title']}\n- Reason: requires code change; not handled by autonomous loop\n\n"
            )
            summary.append({"id": h["id"], "verdict": "deferred"})
            continue

        baseline = load_json(BASELINE_PATH)
        host_section = baseline.get(args.host, {}).get("presets", {})
        baseline_preset_name = h["baseline_preset"]
        if baseline_preset_name not in host_section:
            print(f"[loop] {h['id']}: baseline preset {baseline_preset_name} missing on host {args.host}; skipping", flush=True)
            summary.append({"id": h["id"], "verdict": "no_baseline"})
            continue

        baseline_data = host_section[baseline_preset_name]
        print(f"\n[loop] hypothesis {h['id']}: {h['title']}", flush=True)
        print(f"[loop]   baseline: {baseline_data['tok_per_sec']} tok/s, {baseline_data['peak_vram_mb']} MB", flush=True)

        result = run_bench(h["test_preset"], args.dry_run)
        if result is None:
            verdict, reason = "inconclusive", "bench run failed or was dry-run"
        else:
            verdict, reason = compare(result, baseline_data, h)

        print(f"[loop]   verdict: {verdict} — {reason}", flush=True)
        ts = dt.datetime.now().isoformat(timespec="seconds")
        if result:
            metric_block = (
                f"  - tok/s: {baseline_data['tok_per_sec']:.2f} → {result['tok_per_sec']:.2f}\n"
                f"  - peak VRAM (MB): {baseline_data['peak_vram_mb']} → {result['peak_vram_mb']}\n"
                f"  - step ms (median): {baseline_data['step_ms_median']:.1f} → {result['step_ms_median']:.1f}\n"
                f"  - GPU util: {baseline_data['mean_gpu_util']:.1f}% → {result.get('mean_gpu_util', 0):.1f}%\n"
            )
        else:
            metric_block = "  - no run data\n"
        append_perf_log(
            f"## [{ts}] {h['id']} — {verdict.upper()}\n"
            f"- {h['title']}\n"
            f"- baseline preset: `{baseline_preset_name}`\n"
            f"- test preset: `{h['test_preset']}`\n"
            f"{metric_block}"
            f"- reason: {reason}\n\n"
        )
        summary.append({"id": h["id"], "verdict": verdict, "reason": reason})

        if verdict == "accept" and not args.dry_run:
            update_baseline(args.host, h["test_preset"], result)
            print(f"[loop]   baseline updated for {h['test_preset']}", flush=True)

        # Cooldown between runs so GPU temps stabilize.
        if not args.dry_run:
            time.sleep(COOLDOWN_SECONDS)

    print("\n[loop] === SUMMARY ===", flush=True)
    for s in summary:
        print(f"  {s['id']}: {s['verdict']}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
